### ISSUE TITLE
Bar on top is covering child tableViewControllers

### ISSUE THREAD

**Issue by MhmdRizk** [uias/Tabman#308] opened 2018-07-11 12:11 UTC
### Issue Description

I have a tabman controller having two child table view controllers , and the bar location is on top,
anyway, when I scroll the pages tabman acts normally , if I tapped any item in the bar tabman scrolls to its corresponding page but the bar is covering the child page.

### Other useful things

![simulator screen shot - iphone 6 - 2018-07-11 at 15 04 17](https://user-images.githubusercontent.com/31275366/42570431-8987c322-851c-11e8-8a9b-03cfd905c981.png)

![simulator screen shot - iphone 6 - 2018-07-11 at 15 04 19](https://user-images.githubusercontent.com/31275366/42570460-9f508b26-851c-11e8-84c2-0cdab173641c.png)

**Comment by norrisboat** [comment] 2018-07-11 14:29
I have the same issue on version 1.9.1

**Comment by msaps** [comment] 2018-07-12 07:58
@MhmdRizk @norrisboat will check it out 💪

**Comment by msaps** [comment] 2018-07-17 13:57
@MhmdRizk @norrisboat could either of you maybe provide a demo project where this is reproducible? I'm finding it hard to reproduce and as ever this stuff is really dependent on view hierarchy.

Would be much appreciated  👍

**Comment by msaps** [comment] 2018-08-05 14:12
@MhmdRizk @norrisboat please try using AutoInsetter [1.2.6](https://github.com/uias/AutoInsetter/releases/tag/1.2.6) - I believe this is a duplicate of #316 and related to constraining the `UIScrollView`to the safe area.

**Closed** 2018-08-09 09:08 UTC
Labels: autoinsetter, bug
