### ISSUE TITLE
Scrolling to top of scrollView when performing automatic insets

### ISSUE THREAD

**Issue by enhancient** [uias/Tabman#80] opened 2017-06-06 05:06 UTC
Hi,

I'm having an issue when using hidesBarOnSwipe in a navigation controller where swiping down to reveal the bar again causes insetChildViewControllerIfNeeded(_ childViewController: UIViewController?) to be called and the child scrollView moves to the top of the content.

It seems that this function is also adjusting the contentOffset, but I think there might be a bug. Is this line:

`
contentOffset.y = -requiredContentInset.top
`

meant to be:

`contentOffset.y -= requiredContentInset.top`

Making this change fixed the problem for me.

Thanks!

**Comment by msaps** [comment] 2017-06-06 08:08
Hi, 

Certainly sounds like a bug, I'll take a look and see what I can find..

In the mean time, disabling the auto-insetting behaviour with `automaticallyAdjustsChildScrollViewInsets` and manually insetting your scroll views might be the best approach. 

Cheers!

**Comment by msaps** [comment] 2017-06-27 13:52
I've created a demo project which displays this issue. Can be reproduced by scrolling down the table view in child view controllers and then performing an upwards scroll gesture. The table view's `contentOffset` will be reset to `.zero` when the `UINavigationBar` re-appears. 

I believe this may be due to automatic insetting being applied during `viewDidLayoutSubviews()`. A fix will need to be applied so that this does not reset or mutate `contentOffset` incorrectly.

[Tabman-Test.zip](https://github.com/uias/Tabman/files/1105483/Tabman-Test.zip)

**Comment by msaps** [comment] 2017-07-10 12:30
This is now fixed as of [0.7.2](https://github.com/uias/Tabman/releases/tag/0.7.2) 🎉

**Closed by msaps** 2017-07-10 12:30 UTC
Labels: bug, fixed
