### ISSUE TITLE
Navigation Controller + Tab Man + Scroll View

### ISSUE THREAD

**Issue by markuplab** [uias/Tabman#127] opened 2017-08-09 11:18 UTC
I have structure as in issue name and have a question. 
All content inside scroll view start under tabs, i need add extra top padding for that.
How i can fix it?

**Comment by msaps** [comment] 2017-08-11 09:21
Hi @markuplab 

Tabman should automatically inset any content underneath the bar in the child view controllers. Would you be able to share a screenshot of the behaviour you are seeing?

**Comment by digitaltoad** [comment] 2017-08-11 19:01
I'm having the same problem. If Tabman say in a controller that is pushed to using a navigation controller, the insets are not calculated correctly. If I were to present modally, then everything works. I've gotten around the issue by just calculating them by hand.

**Comment by digitaltoad** [comment] 2017-08-11 19:07
I should say that using a `Container` partially fixes the problem in that views with child `UITableView` are adjusted correctly, but views with `UIScrollView` are not. I took a quick look at the code around auto adjusting insets and honestly I'm not sure I see where the problem is. Using the insets provided by `requiredInsets` still adjusts the insets properly if I manually adjust.

**Comment by msaps** [comment] 2017-08-15 13:49
@digitaltoad I'll see if I can reproduce and find a fix. 

There can be quite a few annoying lifecycle issues with UIKit with insetting and adjusting `contentInset` at the right time etc. If you have a demo project or anything reproducing the issue it would be much appreciated. 👍

**Comment by msaps** [comment] 2017-10-23 10:32
Hopefully this should be fixed in the latest versions (done a bit of work on insetting). If not I will re-open 🤞

**Closed by msaps** 2017-10-23 10:32 UTC
Labels: bug
