### ISSUE TITLE
CocoaPods error

### ISSUE THREAD

**Issue by DoubleJ87** [uias/Tabman#28] opened 2017-03-23 15:13 UTC
I got error message when I Install to pod 'Tabman'

Analyzing dependencies
[!] There are only pre-release versions available satisfying the following requirements:

	'Tabman', '>= 0'

You should explicitly specify the version in order to install a pre-release version

**Comment by msaps** [comment] 2017-03-23 15:16
Duplicate of #26

**Closed by msaps** 2017-03-23 15:16 UTC
