### ISSUE TITLE
How to update Tabbar items title dynamically if come into focus.

### ISSUE THREAD

**Issue by aman198** [uias/Tabman#258] opened 2018-02-18 17:53 UTC
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by msaps** [comment] 2018-03-04 11:39
Assume this is a duplicate of #252

**Closed by msaps** 2018-03-04 11:39 UTC
