### ISSUE TITLE
Crash when calling addBarButtons() with EXC_BAD_ACCESS error

### ISSUE THREAD

**Issue by devdork** [uias/Tabman#333] opened 2018-10-04 09:23 UTC
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Tabman 1.10.0 and 1.10.1 have the same issue, app crashed within the below function in the `TabmanButtonBar.swift` file:
```
 internal func addBarButtons(toView view: UIView,
                                items: [TabmanBar.Item],
                                customize: TabmanButtonBarItemCustomize) {
        var previousButton: UIButton?
        for (index, item) in items.enumerated() { // <- EXC_BAD_ACCESS
           //...
```
Did the items get released before the loop iteration?
### Other useful things
Tabman 1.9.2 works just fine, not sure what caused the issue.

**Comment by msaps** [comment] 2018-10-04 13:45
@devdork @flashadvanced think this is a duplicate of #328 - but can't for the life of me figure it out 😅

I can't seem to reproduce it and also nothing changed (other than Swift 4.2 syntax) in 1.9.x -> 1.10.x. Any more pointers / demo projects for reproduction would be really appreciated.

**Comment by msaps** [comment] 2018-10-04 14:30
@devdork @flashadvanced could you see if [1.10.2](https://github.com/uias/Tabman/releases/tag/1.10.2) improves anything? Cleaned a couple of things up.

**Comment by flashadvanced** [comment] 2018-10-04 16:19
Hey @msaps thanks for the quick answer.

I just realized I haven't updated my project to Swift 4.2 yet! After updating it worked like a charm.
1.10.2 still crashes for Swift 4.0 projects this time with `signal SIGABRT`.

Cheers!

**Closed** 2018-10-08 17:57 UTC
Labels: bug
