### ISSUE TITLE
Problem with switching tabs

### ISSUE THREAD

**Issue by OxMay** [uias/Tabman#327] opened 2018-09-28 07:41 UTC
Hello.
When you quickly switch tabs, there is a problem as in the screenshot. Also, the element freezes and stops processing clicks.
Help pls

![img_0075](https://user-images.githubusercontent.com/26002473/46194784-11790300-c30b-11e8-8754-73eaaa98a260.jpeg)

**Comment by msaps** [comment] 2018-10-03 09:06
@OxMay is this reproducible with intense gesturing (on the page view controller) or by tapping the tabs quickly?

**Comment by OxMay** [comment] 2018-10-03 12:59
@msaps, this issue occurs when you quickly tapping the tabs.

**Comment by msaps** [comment] 2018-12-12 20:13
Closing due to the release of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not, please open a new issue. 🙂

**Closed by msaps** 2018-12-12 20:13 UTC
Labels: bug
