### ISSUE TITLE
There is a white space above my child controllers

### ISSUE THREAD

**Issue by junweimah** [uias/Tabman#264] opened 2018-03-21 03:40 UTC
[Coming from](https://github.com/uias/Tabman/issues/259#issuecomment-374729711)

So I have solved the bug stated there, now I am using these codes in my `initializeViewControllers` : 

```
let storyboard = UIStoryboard(name: "Landing", bundle: Bundle.main)
        var viewControllers = [UIViewController]()
        var barItems = [Item]()

        for index in 0 ..< count {
            var viewControllerChild = UIViewController()
            switch index{
            case 0:
                viewControllerChild = storyboard.instantiateViewController(withIdentifier: "Me_Favourites_CollectionView_SBID") as! MeFavouritesCollectionViewController
                barItems.append(Item(title: StringResource.Favourites))
            case 1:
                viewControllerChild = storyboard.instantiateViewController(withIdentifier: "Wallet_Reload_SBID") as! WalletReloadViewController
                barItems.append(Item(title: StringResource.Vouchers))
            case 2:
                viewControllerChild = storyboard.instantiateViewController(withIdentifier: "Me_Events_CollectionView_SBID") as! MeEventsCollectionViewController
                barItems.append(Item(title: StringResource.Events))
            default :
                break
            }
            //            viewController.index = index + 1
            viewControllers.append(viewControllerChild)
        }
        
        bar.items = barItems
        self.viewControllers = viewControllers
```

When I land on my parent vc, there is a white space between the child and the custom UIView from the parent vc. And scrolling left and right will remove the white space. I have recorded 2 videos and sent you through email, please have a look.

**Comment by electic** [comment] 2018-03-21 21:31
I am having this issue as well. Did anyone find a fix for this?

**Comment by msaps** [comment] 2018-03-21 21:42
@electic @junweimah is this present on the later version of AutoInsetter (1.2.2)? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by electic** [comment] 2018-03-21 21:52
So I just forced updated the podfile to 1.2.2 and yah, it is still there.

**Comment by electic** [comment] 2018-03-21 21:57
So here is the intital state:

https://pasteboard.co/HcZ1d8P.jpg

I scroll down and then I then slighly wiggle the pager.

https://pasteboard.co/HcZ1qPW.jpg

Notice the content in moves in this shot. Then I scroll up and you see the gap.

https://pasteboard.co/HcZ0Tnv.jpg

**Comment by electic** [comment] 2018-03-21 22:07
So I got it to work by changing something in the tabman file:

`    open override func viewDidLoad() {
        super.viewDidLoad()
        
        // configure for auto insetting
        //self.automaticallyAdjustsScrollViewInsets = !automaticallyAdjustsChildViewInsets
        autoInsetter.isEnabled = false
`

This seems to fix it. Not sure if this helps :/

**Comment by junweimah** [comment] 2018-03-22 02:34
@electic 

Where should I add this code to? Which tabman file?

**Comment by junweimah** [comment] 2018-03-22 02:35
@msaps Did you see my email I sent you yesterday? I recorded some videos for better illustrations

**Comment by electic** [comment] 2018-03-22 06:55
I think the issue is that the indenting engine is not accounting for some scenarious. For example in my case, I have:

UIScrollView
-UIView
-- UILabbel
--UILable
--UITableView

In this case, I would assume the indenting engine would skip trying to indent the UITableView and indent the parent scrollview or the parent uiview. At least that is what I understand for the code. I have another dashboard in the second UIViewCongtroller where it is:

- UIScrollView
--UIView
---UIVIew (Graph Comentent)
---UILabel
---UITableView

In this case, I notice it indents the uitabbleview in the middle of the view. So, I think it is something to do with the auto indentation engine and I am not to familiar enough to fix it. For now, to get around this I have disabled the autoindentation and in my constructor just added a property to optionally set padding on the top. Hope it helps.

**Comment by junweimah** [comment] 2018-03-22 07:06
@electic 
wow I am too new as an iOS developer to understand all this. Hopefully this is a bug that can, and will be fixed.

By the way you said you changed a file : 

> ```
>     // configure for auto insetting
>     //self.automaticallyAdjustsScrollViewInsets = !automaticallyAdjustsChildViewInsets
>     autoInsetter.isEnabled = false
> ```

Which file is this that you changed?

**Comment by electic** [comment] 2018-03-22 07:09
So basically before you set the datasource for Tabman, put in this line:

`        self.automaticallyAdjustsChildViewInsets = false

That will disable the autoinsetter engine. Then you can manually just move your content down 45 pts.

**Comment by junweimah** [comment] 2018-03-22 07:36
Thanks. 

After some effort i got it working, have to manually set top value for child

**Comment by msaps** [comment] 2018-03-22 08:31
@electic @junweimah  will take a look at the AutoInsetting logic, and see if I can fix it. Ideally it would handle these sort of scenarios, because it should attempt to find the relative position of the view in the root superview and inset as necessary.

**Comment by electic** [comment] 2018-03-22 08:41
@msaps, happy to give you the code or we can do a google hangout as well. Whatever helps debug the issue and saves time :) I use snapkit, so reviewing the code shouldn't be too bad.

**Comment by msaps** [comment] 2018-03-22 18:53
@electic would you be able to see if you can reproduce the issue in this demo project? I've reproduced the kind of layout you are using with a default Tabman setup:

[Tabman-TopInsetTest.zip](https://github.com/uias/Tabman/files/1838857/Tabman-TopInsetTest.zip)

**Comment by electic** [comment] 2018-03-23 02:39
Getting some errors during compiling:

`<unknown>:0: error: no such file or directory: '/Users/merrick/Dev/Projects/AutoInsetter/Sources/AutoInsetter/AutoInsetSpec.swift'
<unknown>:0: error: no such file or directory: '/Users/merrick/Dev/Projects/AutoInsetter/Sources/AutoInsetter/AutoInsetter.swift'
<unknown>:0: error: no such file or directory: '/Users/merrick/Dev/Projects/AutoInsetter/Sources/AutoInsetter/Utilities/UIScrollView+Interaction.swift'
<unknown>:0: error: no such file or directory: '/Users/merrick/Dev/Projects/AutoInsetter/Sources/AutoInsetter/Utilities/UIViewController+ScrollViewDetection.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1`

**Comment by msaps** [comment] 2018-03-23 09:44
@electic apologies - was using local pods 😅.

[Tabman-TopInsetTest.zip](https://github.com/uias/Tabman/files/1840971/Tabman-TopInsetTest.zip)

**Comment by electic** [comment] 2018-03-24 08:49
Hi, I use snapkit. But either way, this project has the gap as well. 

https://pasteboard.co/Hdma69A.png

**Comment by msaps** [comment] 2018-03-25 16:01
@junweimah @electic - should now be fixed as of AutoInsetter [v1.2.3](https://github.com/uias/AutoInsetter/releases/tag/1.2.3). 

The issue was caused by the calculations that decide how much to inset a view by based on its relative position using the incorrect superview in the hierarchy. Let me know how you get on!

**Comment by electic** [comment] 2018-03-25 22:53
It does look like it solves the problem. Going to keep testing it today, will let you know if I find something. Thanks msaps and thank you for the great component!

**Comment by junweimah** [comment] 2018-03-26 03:03
Sorry I don't know how merging works. Do I need to remove the pod and pod install again? How do I get the latest code?

**Comment by electic** [comment] 2018-03-26 05:56
The latest code is in AutoSetter. The pod has been released. To force it to update, just add the AutoSetter pod. Here:

`pod 'Tabman', '1.6.0'
    pod 'AutoInsetter', '1.2.3'
`

**Comment by msaps** [comment] 2018-03-26 07:07
@junweimah @electic it’s probably best to use the constraints of Tabman for versioning. `Pod Tabman ~1.6` is sufficient.

To update AutoInsetter, rum `pod update AutoInsetter`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2018-03-29 15:05 UTC
Labels: autoinsetter, bug
